language: node_js
node_js:
  - 14.16.0
script:
  - "npm run test"
deploy:
  provider: heroku
  api_key:
    secure: <your-api-key>
  app:
    main: fullstack-travis-demo
    staging: fullstack-travis-demo
  on:
    repo: jmsherry/full-stack-shop-app